# Site settings
title: Wellness Blog | Juice Plus + Event
email: errin.johnson@gmail.com
description: My simple blog.
baseurl: "/wellness-blog"
url: ""
twitter_username: errinjohnson64
avatar: "https://pbs.twimg.com/profile_images/2160145196/2011wdanandnashvilleconference_183_400x400.JPG" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "errin johnson" # Set default author name
      categories: "wellness, juice plus"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
